# Generated by Django 3.0.6 on 2020-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multierp', '0002_auto_20200913_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finance_handler',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='operation_handler',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_registration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_handler',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
