# Generated by Django 3.0.6 on 2020-09-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multierp', '0003_auto_20200913_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finance_handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fin_handler', to='multierp.Muser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operation_handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oprn_handler', to='multierp.Muser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_reg', to='multierp.Muser'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ship_handler', to='multierp.Muser'),
        ),
    ]
