# Generated by Django 3.0.6 on 2020-09-21 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multierp', '0006_auto_20200914_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_from_user', to='multierp.Order'),
        ),
    ]
